// Code generated by ent, DO NOT EDIT.

package ent

// set field if value is not empty. e.g. string does not equal to ""
func (c *CategoryUpdate) SetNotEmptySort(value uint32) *CategoryUpdate {
	if value != 0 {
		return c.SetSort(value)
	}
	return c
}

// set field if value is not empty. e.g. string does not equal to ""
func (c *CategoryUpdateOne) SetNotEmptySort(value uint32) *CategoryUpdateOne {
	if value != 0 {
		return c.SetSort(value)
	}
	return c
}

// set field if value is not empty. e.g. string does not equal to ""
func (c *CategoryUpdate) SetNotEmptyStatus(value uint8) *CategoryUpdate {
	if value != 0 {
		return c.SetStatus(value)
	}
	return c
}

// set field if value is not empty. e.g. string does not equal to ""
func (c *CategoryUpdateOne) SetNotEmptyStatus(value uint8) *CategoryUpdateOne {
	if value != 0 {
		return c.SetStatus(value)
	}
	return c
}

// set field if value is not empty. e.g. string does not equal to ""
func (c *CategoryUpdate) SetNotEmptyName(value string) *CategoryUpdate {
	if value != "" {
		return c.SetName(value)
	}
	return c
}

// set field if value is not empty. e.g. string does not equal to ""
func (c *CategoryUpdateOne) SetNotEmptyName(value string) *CategoryUpdateOne {
	if value != "" {
		return c.SetName(value)
	}
	return c
}

// set field if value is not empty. e.g. string does not equal to ""
func (c *CategoryUpdate) SetNotEmptySlug(value string) *CategoryUpdate {
	if value != "" {
		return c.SetSlug(value)
	}
	return c
}

// set field if value is not empty. e.g. string does not equal to ""
func (c *CategoryUpdateOne) SetNotEmptySlug(value string) *CategoryUpdateOne {
	if value != "" {
		return c.SetSlug(value)
	}
	return c
}

// set field if value is not empty. e.g. string does not equal to ""
func (c *CategoryUpdate) SetNotEmptyIcon(value string) *CategoryUpdate {
	if value != "" {
		return c.SetIcon(value)
	}
	return c
}

// set field if value is not empty. e.g. string does not equal to ""
func (c *CategoryUpdateOne) SetNotEmptyIcon(value string) *CategoryUpdateOne {
	if value != "" {
		return c.SetIcon(value)
	}
	return c
}

// set field if value is not empty. e.g. string does not equal to ""
func (c *CategoryUpdate) SetNotEmptyDesc(value string) *CategoryUpdate {
	if value != "" {
		return c.SetDesc(value)
	}
	return c
}

// set field if value is not empty. e.g. string does not equal to ""
func (c *CategoryUpdateOne) SetNotEmptyDesc(value string) *CategoryUpdateOne {
	if value != "" {
		return c.SetDesc(value)
	}
	return c
}

// set field if value is not empty. e.g. string does not equal to ""
func (c *CategoryUpdate) SetNotEmptyType(value uint32) *CategoryUpdate {
	if value != 0 {
		return c.SetType(value)
	}
	return c
}

// set field if value is not empty. e.g. string does not equal to ""
func (c *CategoryUpdateOne) SetNotEmptyType(value uint32) *CategoryUpdateOne {
	if value != 0 {
		return c.SetType(value)
	}
	return c
}

// set field if value is not empty. e.g. string does not equal to ""
func (c *CommentUpdate) SetNotEmptyStatus(value uint8) *CommentUpdate {
	if value != 0 {
		return c.SetStatus(value)
	}
	return c
}

// set field if value is not empty. e.g. string does not equal to ""
func (c *CommentUpdateOne) SetNotEmptyStatus(value uint8) *CommentUpdateOne {
	if value != 0 {
		return c.SetStatus(value)
	}
	return c
}

// set field if value is not empty. e.g. string does not equal to ""
func (c *CommentUpdate) SetNotEmptyContent(value string) *CommentUpdate {
	if value != "" {
		return c.SetContent(value)
	}
	return c
}

// set field if value is not empty. e.g. string does not equal to ""
func (c *CommentUpdateOne) SetNotEmptyContent(value string) *CommentUpdateOne {
	if value != "" {
		return c.SetContent(value)
	}
	return c
}

// set field if value is not empty. e.g. string does not equal to ""
func (c *CommentUpdate) SetNotEmptyServiceUUID(value string) *CommentUpdate {
	if value != "" {
		return c.SetServiceUUID(value)
	}
	return c
}

// set field if value is not empty. e.g. string does not equal to ""
func (c *CommentUpdateOne) SetNotEmptyServiceUUID(value string) *CommentUpdateOne {
	if value != "" {
		return c.SetServiceUUID(value)
	}
	return c
}

// set field if value is not empty. e.g. string does not equal to ""
func (c *CommentUpdate) SetNotEmptyUserUUID(value string) *CommentUpdate {
	if value != "" {
		return c.SetUserUUID(value)
	}
	return c
}

// set field if value is not empty. e.g. string does not equal to ""
func (c *CommentUpdateOne) SetNotEmptyUserUUID(value string) *CommentUpdateOne {
	if value != "" {
		return c.SetUserUUID(value)
	}
	return c
}

// set field if value is not empty. e.g. string does not equal to ""
func (c *CommentUpdate) SetNotEmptyType(value uint32) *CommentUpdate {
	if value != 0 {
		return c.SetType(value)
	}
	return c
}

// set field if value is not empty. e.g. string does not equal to ""
func (c *CommentUpdateOne) SetNotEmptyType(value uint32) *CommentUpdateOne {
	if value != 0 {
		return c.SetType(value)
	}
	return c
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *ServiceUpdate) SetNotEmptyStatus(value uint8) *ServiceUpdate {
	if value != 0 {
		return s.SetStatus(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *ServiceUpdateOne) SetNotEmptyStatus(value uint8) *ServiceUpdateOne {
	if value != 0 {
		return s.SetStatus(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *ServiceUpdate) SetNotEmptyTitle(value string) *ServiceUpdate {
	if value != "" {
		return s.SetTitle(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *ServiceUpdateOne) SetNotEmptyTitle(value string) *ServiceUpdateOne {
	if value != "" {
		return s.SetTitle(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *ServiceUpdate) SetNotEmptyDesc(value string) *ServiceUpdate {
	if value != "" {
		return s.SetDesc(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *ServiceUpdateOne) SetNotEmptyDesc(value string) *ServiceUpdateOne {
	if value != "" {
		return s.SetDesc(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *ServiceUpdate) SetNotEmptyContent(value string) *ServiceUpdate {
	if value != "" {
		return s.SetContent(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *ServiceUpdateOne) SetNotEmptyContent(value string) *ServiceUpdateOne {
	if value != "" {
		return s.SetContent(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *ServiceUpdate) SetNotEmptyCategoryID(value uint64) *ServiceUpdate {
	if value != 0 {
		return s.SetCategoryID(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *ServiceUpdateOne) SetNotEmptyCategoryID(value uint64) *ServiceUpdateOne {
	if value != 0 {
		return s.SetCategoryID(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *ServiceUpdate) SetNotEmptyAuthorUUID(value string) *ServiceUpdate {
	if value != "" {
		return s.SetAuthorUUID(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *ServiceUpdateOne) SetNotEmptyAuthorUUID(value string) *ServiceUpdateOne {
	if value != "" {
		return s.SetAuthorUUID(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *ServiceUpdate) SetNotEmptyCover(value string) *ServiceUpdate {
	if value != "" {
		return s.SetCover(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *ServiceUpdateOne) SetNotEmptyCover(value string) *ServiceUpdateOne {
	if value != "" {
		return s.SetCover(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *ServiceUpdate) SetNotEmptyDocument(value string) *ServiceUpdate {
	if value != "" {
		return s.SetDocument(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *ServiceUpdateOne) SetNotEmptyDocument(value string) *ServiceUpdateOne {
	if value != "" {
		return s.SetDocument(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *ServiceUpdate) SetNotEmptyVersion(value string) *ServiceUpdate {
	if value != "" {
		return s.SetVersion(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *ServiceUpdateOne) SetNotEmptyVersion(value string) *ServiceUpdateOne {
	if value != "" {
		return s.SetVersion(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *ServiceUpdate) SetNotEmptyType(value uint32) *ServiceUpdate {
	if value != 0 {
		return s.SetType(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *ServiceUpdateOne) SetNotEmptyType(value uint32) *ServiceUpdateOne {
	if value != 0 {
		return s.SetType(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *ServiceUpdate) SetNotEmptyPrice(value uint32) *ServiceUpdate {
	if value != 0 {
		return s.SetPrice(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *ServiceUpdateOne) SetNotEmptyPrice(value uint32) *ServiceUpdateOne {
	if value != 0 {
		return s.SetPrice(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *ServiceUpdate) SetNotEmptyView(value uint64) *ServiceUpdate {
	if value != 0 {
		return s.SetView(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *ServiceUpdateOne) SetNotEmptyView(value uint64) *ServiceUpdateOne {
	if value != 0 {
		return s.SetView(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *SitemetaUpdate) SetNotEmptyKey(value string) *SitemetaUpdate {
	if value != "" {
		return s.SetKey(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *SitemetaUpdateOne) SetNotEmptyKey(value string) *SitemetaUpdateOne {
	if value != "" {
		return s.SetKey(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *SitemetaUpdate) SetNotEmptyValue(value string) *SitemetaUpdate {
	if value != "" {
		return s.SetValue(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *SitemetaUpdateOne) SetNotEmptyValue(value string) *SitemetaUpdateOne {
	if value != "" {
		return s.SetValue(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (v *VersionUpdate) SetNotEmptyStatus(value uint8) *VersionUpdate {
	if value != 0 {
		return v.SetStatus(value)
	}
	return v
}

// set field if value is not empty. e.g. string does not equal to ""
func (v *VersionUpdateOne) SetNotEmptyStatus(value uint8) *VersionUpdateOne {
	if value != 0 {
		return v.SetStatus(value)
	}
	return v
}

// set field if value is not empty. e.g. string does not equal to ""
func (v *VersionUpdate) SetNotEmptyTitle(value string) *VersionUpdate {
	if value != "" {
		return v.SetTitle(value)
	}
	return v
}

// set field if value is not empty. e.g. string does not equal to ""
func (v *VersionUpdateOne) SetNotEmptyTitle(value string) *VersionUpdateOne {
	if value != "" {
		return v.SetTitle(value)
	}
	return v
}

// set field if value is not empty. e.g. string does not equal to ""
func (v *VersionUpdate) SetNotEmptyContent(value string) *VersionUpdate {
	if value != "" {
		return v.SetContent(value)
	}
	return v
}

// set field if value is not empty. e.g. string does not equal to ""
func (v *VersionUpdateOne) SetNotEmptyContent(value string) *VersionUpdateOne {
	if value != "" {
		return v.SetContent(value)
	}
	return v
}

// set field if value is not empty. e.g. string does not equal to ""
func (v *VersionUpdate) SetNotEmptyServiceUUID(value uint64) *VersionUpdate {
	if value != 0 {
		return v.SetServiceUUID(value)
	}
	return v
}

// set field if value is not empty. e.g. string does not equal to ""
func (v *VersionUpdateOne) SetNotEmptyServiceUUID(value uint64) *VersionUpdateOne {
	if value != 0 {
		return v.SetServiceUUID(value)
	}
	return v
}

// set field if value is not empty. e.g. string does not equal to ""
func (v *VersionUpdate) SetNotEmptyURL(value string) *VersionUpdate {
	if value != "" {
		return v.SetURL(value)
	}
	return v
}

// set field if value is not empty. e.g. string does not equal to ""
func (v *VersionUpdateOne) SetNotEmptyURL(value string) *VersionUpdateOne {
	if value != "" {
		return v.SetURL(value)
	}
	return v
}
