// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Coder-ZhaoLu/pinkmoe_rpc/ent/category"
	"github.com/Coder-ZhaoLu/pinkmoe_rpc/ent/comment"
	"github.com/Coder-ZhaoLu/pinkmoe_rpc/ent/schema"
	"github.com/Coder-ZhaoLu/pinkmoe_rpc/ent/service"
	"github.com/Coder-ZhaoLu/pinkmoe_rpc/ent/sitemeta"
	uuid "github.com/gofrs/uuid/v5"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	categoryMixin := schema.Category{}.Mixin()
	categoryMixinFields0 := categoryMixin[0].Fields()
	_ = categoryMixinFields0
	categoryMixinFields1 := categoryMixin[1].Fields()
	_ = categoryMixinFields1
	categoryMixinFields2 := categoryMixin[2].Fields()
	_ = categoryMixinFields2
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescCreatedAt is the schema descriptor for created_at field.
	categoryDescCreatedAt := categoryMixinFields0[1].Descriptor()
	// category.DefaultCreatedAt holds the default value on creation for the created_at field.
	category.DefaultCreatedAt = categoryDescCreatedAt.Default.(func() time.Time)
	// categoryDescUpdatedAt is the schema descriptor for updated_at field.
	categoryDescUpdatedAt := categoryMixinFields0[2].Descriptor()
	// category.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	category.DefaultUpdatedAt = categoryDescUpdatedAt.Default.(func() time.Time)
	// category.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	category.UpdateDefaultUpdatedAt = categoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// categoryDescSort is the schema descriptor for sort field.
	categoryDescSort := categoryMixinFields1[0].Descriptor()
	// category.DefaultSort holds the default value on creation for the sort field.
	category.DefaultSort = categoryDescSort.Default.(uint32)
	// categoryDescStatus is the schema descriptor for status field.
	categoryDescStatus := categoryMixinFields2[0].Descriptor()
	// category.DefaultStatus holds the default value on creation for the status field.
	category.DefaultStatus = categoryDescStatus.Default.(uint8)
	commentMixin := schema.Comment{}.Mixin()
	commentMixinFields0 := commentMixin[0].Fields()
	_ = commentMixinFields0
	commentMixinFields1 := commentMixin[1].Fields()
	_ = commentMixinFields1
	commentFields := schema.Comment{}.Fields()
	_ = commentFields
	// commentDescCreatedAt is the schema descriptor for created_at field.
	commentDescCreatedAt := commentMixinFields0[1].Descriptor()
	// comment.DefaultCreatedAt holds the default value on creation for the created_at field.
	comment.DefaultCreatedAt = commentDescCreatedAt.Default.(func() time.Time)
	// commentDescUpdatedAt is the schema descriptor for updated_at field.
	commentDescUpdatedAt := commentMixinFields0[2].Descriptor()
	// comment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	comment.DefaultUpdatedAt = commentDescUpdatedAt.Default.(func() time.Time)
	// comment.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	comment.UpdateDefaultUpdatedAt = commentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// commentDescStatus is the schema descriptor for status field.
	commentDescStatus := commentMixinFields1[0].Descriptor()
	// comment.DefaultStatus holds the default value on creation for the status field.
	comment.DefaultStatus = commentDescStatus.Default.(uint8)
	// commentDescType is the schema descriptor for type field.
	commentDescType := commentFields[3].Descriptor()
	// comment.DefaultType holds the default value on creation for the type field.
	comment.DefaultType = commentDescType.Default.(uint32)
	// commentDescID is the schema descriptor for id field.
	commentDescID := commentMixinFields0[0].Descriptor()
	// comment.DefaultID holds the default value on creation for the id field.
	comment.DefaultID = commentDescID.Default.(func() uuid.UUID)
	serviceMixin := schema.Service{}.Mixin()
	serviceMixinFields0 := serviceMixin[0].Fields()
	_ = serviceMixinFields0
	serviceMixinFields1 := serviceMixin[1].Fields()
	_ = serviceMixinFields1
	serviceFields := schema.Service{}.Fields()
	_ = serviceFields
	// serviceDescCreatedAt is the schema descriptor for created_at field.
	serviceDescCreatedAt := serviceMixinFields0[1].Descriptor()
	// service.DefaultCreatedAt holds the default value on creation for the created_at field.
	service.DefaultCreatedAt = serviceDescCreatedAt.Default.(func() time.Time)
	// serviceDescUpdatedAt is the schema descriptor for updated_at field.
	serviceDescUpdatedAt := serviceMixinFields0[2].Descriptor()
	// service.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	service.DefaultUpdatedAt = serviceDescUpdatedAt.Default.(func() time.Time)
	// service.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	service.UpdateDefaultUpdatedAt = serviceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// serviceDescStatus is the schema descriptor for status field.
	serviceDescStatus := serviceMixinFields1[0].Descriptor()
	// service.DefaultStatus holds the default value on creation for the status field.
	service.DefaultStatus = serviceDescStatus.Default.(uint8)
	// serviceDescType is the schema descriptor for type field.
	serviceDescType := serviceFields[5].Descriptor()
	// service.DefaultType holds the default value on creation for the type field.
	service.DefaultType = serviceDescType.Default.(uint32)
	// serviceDescView is the schema descriptor for view field.
	serviceDescView := serviceFields[7].Descriptor()
	// service.DefaultView holds the default value on creation for the view field.
	service.DefaultView = serviceDescView.Default.(uint64)
	// serviceDescID is the schema descriptor for id field.
	serviceDescID := serviceMixinFields0[0].Descriptor()
	// service.DefaultID holds the default value on creation for the id field.
	service.DefaultID = serviceDescID.Default.(func() uuid.UUID)
	sitemetaMixin := schema.Sitemeta{}.Mixin()
	sitemetaMixinFields0 := sitemetaMixin[0].Fields()
	_ = sitemetaMixinFields0
	sitemetaFields := schema.Sitemeta{}.Fields()
	_ = sitemetaFields
	// sitemetaDescCreatedAt is the schema descriptor for created_at field.
	sitemetaDescCreatedAt := sitemetaMixinFields0[1].Descriptor()
	// sitemeta.DefaultCreatedAt holds the default value on creation for the created_at field.
	sitemeta.DefaultCreatedAt = sitemetaDescCreatedAt.Default.(func() time.Time)
	// sitemetaDescUpdatedAt is the schema descriptor for updated_at field.
	sitemetaDescUpdatedAt := sitemetaMixinFields0[2].Descriptor()
	// sitemeta.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	sitemeta.DefaultUpdatedAt = sitemetaDescUpdatedAt.Default.(func() time.Time)
	// sitemeta.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	sitemeta.UpdateDefaultUpdatedAt = sitemetaDescUpdatedAt.UpdateDefault.(func() time.Time)
}
