// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Coder-ZhaoLu/pinkmoe_rpc/ent/sitemeta"
)

// SitemetaCreate is the builder for creating a Sitemeta entity.
type SitemetaCreate struct {
	config
	mutation *SitemetaMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (sc *SitemetaCreate) SetCreatedAt(t time.Time) *SitemetaCreate {
	sc.mutation.SetCreatedAt(t)
	return sc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sc *SitemetaCreate) SetNillableCreatedAt(t *time.Time) *SitemetaCreate {
	if t != nil {
		sc.SetCreatedAt(*t)
	}
	return sc
}

// SetUpdatedAt sets the "updated_at" field.
func (sc *SitemetaCreate) SetUpdatedAt(t time.Time) *SitemetaCreate {
	sc.mutation.SetUpdatedAt(t)
	return sc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (sc *SitemetaCreate) SetNillableUpdatedAt(t *time.Time) *SitemetaCreate {
	if t != nil {
		sc.SetUpdatedAt(*t)
	}
	return sc
}

// SetKey sets the "key" field.
func (sc *SitemetaCreate) SetKey(s string) *SitemetaCreate {
	sc.mutation.SetKey(s)
	return sc
}

// SetValue sets the "value" field.
func (sc *SitemetaCreate) SetValue(s string) *SitemetaCreate {
	sc.mutation.SetValue(s)
	return sc
}

// SetID sets the "id" field.
func (sc *SitemetaCreate) SetID(u uint64) *SitemetaCreate {
	sc.mutation.SetID(u)
	return sc
}

// Mutation returns the SitemetaMutation object of the builder.
func (sc *SitemetaCreate) Mutation() *SitemetaMutation {
	return sc.mutation
}

// Save creates the Sitemeta in the database.
func (sc *SitemetaCreate) Save(ctx context.Context) (*Sitemeta, error) {
	sc.defaults()
	return withHooks[*Sitemeta, SitemetaMutation](ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SitemetaCreate) SaveX(ctx context.Context) *Sitemeta {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SitemetaCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SitemetaCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sc *SitemetaCreate) defaults() {
	if _, ok := sc.mutation.CreatedAt(); !ok {
		v := sitemeta.DefaultCreatedAt()
		sc.mutation.SetCreatedAt(v)
	}
	if _, ok := sc.mutation.UpdatedAt(); !ok {
		v := sitemeta.DefaultUpdatedAt()
		sc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *SitemetaCreate) check() error {
	if _, ok := sc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Sitemeta.created_at"`)}
	}
	if _, ok := sc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Sitemeta.updated_at"`)}
	}
	if _, ok := sc.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "Sitemeta.key"`)}
	}
	if _, ok := sc.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "Sitemeta.value"`)}
	}
	return nil
}

func (sc *SitemetaCreate) sqlSave(ctx context.Context) (*Sitemeta, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *SitemetaCreate) createSpec() (*Sitemeta, *sqlgraph.CreateSpec) {
	var (
		_node = &Sitemeta{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(sitemeta.Table, sqlgraph.NewFieldSpec(sitemeta.FieldID, field.TypeUint64))
	)
	if id, ok := sc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := sc.mutation.CreatedAt(); ok {
		_spec.SetField(sitemeta.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := sc.mutation.UpdatedAt(); ok {
		_spec.SetField(sitemeta.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := sc.mutation.Key(); ok {
		_spec.SetField(sitemeta.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := sc.mutation.Value(); ok {
		_spec.SetField(sitemeta.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	return _node, _spec
}

// SitemetaCreateBulk is the builder for creating many Sitemeta entities in bulk.
type SitemetaCreateBulk struct {
	config
	builders []*SitemetaCreate
}

// Save creates the Sitemeta entities in the database.
func (scb *SitemetaCreateBulk) Save(ctx context.Context) ([]*Sitemeta, error) {
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Sitemeta, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SitemetaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SitemetaCreateBulk) SaveX(ctx context.Context) []*Sitemeta {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SitemetaCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SitemetaCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
