// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Coder-ZhaoLu/pinkmoe_rpc/ent/predicate"
	"github.com/Coder-ZhaoLu/pinkmoe_rpc/ent/sitemeta"
)

// SitemetaUpdate is the builder for updating Sitemeta entities.
type SitemetaUpdate struct {
	config
	hooks    []Hook
	mutation *SitemetaMutation
}

// Where appends a list predicates to the SitemetaUpdate builder.
func (su *SitemetaUpdate) Where(ps ...predicate.Sitemeta) *SitemetaUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetUpdatedAt sets the "updated_at" field.
func (su *SitemetaUpdate) SetUpdatedAt(t time.Time) *SitemetaUpdate {
	su.mutation.SetUpdatedAt(t)
	return su
}

// SetKey sets the "key" field.
func (su *SitemetaUpdate) SetKey(s string) *SitemetaUpdate {
	su.mutation.SetKey(s)
	return su
}

// SetValue sets the "value" field.
func (su *SitemetaUpdate) SetValue(s string) *SitemetaUpdate {
	su.mutation.SetValue(s)
	return su
}

// Mutation returns the SitemetaMutation object of the builder.
func (su *SitemetaUpdate) Mutation() *SitemetaMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SitemetaUpdate) Save(ctx context.Context) (int, error) {
	su.defaults()
	return withHooks[int, SitemetaMutation](ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SitemetaUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SitemetaUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SitemetaUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (su *SitemetaUpdate) defaults() {
	if _, ok := su.mutation.UpdatedAt(); !ok {
		v := sitemeta.UpdateDefaultUpdatedAt()
		su.mutation.SetUpdatedAt(v)
	}
}

func (su *SitemetaUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(sitemeta.Table, sitemeta.Columns, sqlgraph.NewFieldSpec(sitemeta.FieldID, field.TypeUint64))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.UpdatedAt(); ok {
		_spec.SetField(sitemeta.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := su.mutation.Key(); ok {
		_spec.SetField(sitemeta.FieldKey, field.TypeString, value)
	}
	if value, ok := su.mutation.Value(); ok {
		_spec.SetField(sitemeta.FieldValue, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sitemeta.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SitemetaUpdateOne is the builder for updating a single Sitemeta entity.
type SitemetaUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SitemetaMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (suo *SitemetaUpdateOne) SetUpdatedAt(t time.Time) *SitemetaUpdateOne {
	suo.mutation.SetUpdatedAt(t)
	return suo
}

// SetKey sets the "key" field.
func (suo *SitemetaUpdateOne) SetKey(s string) *SitemetaUpdateOne {
	suo.mutation.SetKey(s)
	return suo
}

// SetValue sets the "value" field.
func (suo *SitemetaUpdateOne) SetValue(s string) *SitemetaUpdateOne {
	suo.mutation.SetValue(s)
	return suo
}

// Mutation returns the SitemetaMutation object of the builder.
func (suo *SitemetaUpdateOne) Mutation() *SitemetaMutation {
	return suo.mutation
}

// Where appends a list predicates to the SitemetaUpdate builder.
func (suo *SitemetaUpdateOne) Where(ps ...predicate.Sitemeta) *SitemetaUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SitemetaUpdateOne) Select(field string, fields ...string) *SitemetaUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Sitemeta entity.
func (suo *SitemetaUpdateOne) Save(ctx context.Context) (*Sitemeta, error) {
	suo.defaults()
	return withHooks[*Sitemeta, SitemetaMutation](ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SitemetaUpdateOne) SaveX(ctx context.Context) *Sitemeta {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SitemetaUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SitemetaUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (suo *SitemetaUpdateOne) defaults() {
	if _, ok := suo.mutation.UpdatedAt(); !ok {
		v := sitemeta.UpdateDefaultUpdatedAt()
		suo.mutation.SetUpdatedAt(v)
	}
}

func (suo *SitemetaUpdateOne) sqlSave(ctx context.Context) (_node *Sitemeta, err error) {
	_spec := sqlgraph.NewUpdateSpec(sitemeta.Table, sitemeta.Columns, sqlgraph.NewFieldSpec(sitemeta.FieldID, field.TypeUint64))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Sitemeta.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sitemeta.FieldID)
		for _, f := range fields {
			if !sitemeta.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sitemeta.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.UpdatedAt(); ok {
		_spec.SetField(sitemeta.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := suo.mutation.Key(); ok {
		_spec.SetField(sitemeta.FieldKey, field.TypeString, value)
	}
	if value, ok := suo.mutation.Value(); ok {
		_spec.SetField(sitemeta.FieldValue, field.TypeString, value)
	}
	_node = &Sitemeta{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sitemeta.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
