// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// Service is the predicate function for service builders.
type Service func(*sql.Selector)

// Sitemeta is the predicate function for sitemeta builders.
type Sitemeta func(*sql.Selector)

// Version is the predicate function for version builders.
type Version func(*sql.Selector)
